export const SCREENS = {
  BUY: "BUY",
  MY_KITTIES: "MY_KITTIES",
  ALL_KITTIES: "ALL_KITTIES",
  DETAILS: "DETAILS",
};

export const KITTY_ACTIONS = {
  CAN_BUY: "CAN_BUY",
  LOGIN_TO_BUY: "LOGIN_TO_BUY",
  REMOVE_FROM_SALE: "REMOVE_FROM_SALE",
  PUT_ON_SALE: "PUT_ON_SALE",
  TRANSFER: "TRANSFER",
};

// const CONSTS = { SCREENS };
// export default CONSTS;
